on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ vars.DOCKER_PASSWORD }}
  CONTAINER_NAME: golang-devops

permissions:
  contents: read

jobs:
  pre-build:
    runs-on: self-hosted
    steps:
    - name: pre-build
      run: |
        echo "COMMIT_SHA_SHORT=`echo ${GITHUB_SHA} | cut -c1-7`"
      
  build:
    runs-on: self-hosted
    needs: pre-build
    steps:
    - uses: actions/checkout@v3

    - name: build docker image
      run: |
        echo $COMMIT_SHA_SHORT
        #docker build -t $DOCKER_USERNAME/$CONTAINER_NAME:$COMMIT_SHA_SHORT
