on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ vars.DOCKER_PASSWORD }}
  COMMIT_SHA_SHORT: ${{ vars.GITHUB_SHA::6 }}
  CONTAINER_NAME: golang-devops

permissions:
  contents: read

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3

    - name: build docker image
      run: |
        echo $COMMIT_SHA_SHORT
        #docker build -t $DOCKER_USERNAME/$CONTAINER_NAME:$COMMIT_SHA_SHORT
